version: "3.8"

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: clinicms-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: clinicms
      MYSQL_USER: clinicms_user
      MYSQL_PASSWORD: clinicms_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - clinicms-network

  # Backend API
  backend:
    build: ./backend
    container_name: clinicms-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3001
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: clinicms_user
      DB_PASSWORD: clinicms_password
      DB_DATABASE: clinicms
      JWT_SECRET: your_super_secure_jwt_secret_key_here
      FRONTEND_URL: http://localhost
    ports:
      - "3001:3001"
    depends_on:
      - mysql
    networks:
      - clinicms-network

  # Frontend
  frontend:
    build: ./frontend
    container_name: clinicms-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - clinicms-network

volumes:
  mysql_data:

networks:
  clinicms-network:
    driver: bridge
