[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.optimized"

[deploy]
healthcheckPath = "/api"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[[services]]
name = "clinicms-backend" 