[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/api"
healthcheckTimeout = 120
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
startCommand = "npm run railway:start"

[[services]]
name = "clinicms-backend" 