services:
  - type: web
    name: clinicms-backend
    env: node
    plan: free
    buildCommand: cd backend && chmod +x render-build.sh && ./render-build.sh
    startCommand: cd backend && node dist/main.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: MYSQLHOST
        sync: false
      - key: MYSQLPORT
        value: 3306
      - key: MYSQLUSER
        value: root
      - key: MYSQLPASSWORD
        sync: false
      - key: MYSQLDATABASE
        value: railway
      - key: JWT_SECRET
        value: msclinic
      - key: JWT_EXPIRES_IN
        value: 24h
