[build]
builder = "dockerfile"

[deploy]
startCommand = "npm run start:prod"
healthcheckPath = "/api"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[[services]]
name = "clinicms-backend" 